name: PR Checks

on: # Rebuild any PRs and main branch changes
  push:
    branches:
      - main
  pull_request:

step-node: &setup-node
  - uses: actions/setup-node@v3
    with:
      node-version: 14.x
      cache: yarn



jobs:

  install-node-modules:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - <<: *setup-node
      - name: Validate cache
        run: yarn install --frozen-lockfile

  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v3
      - <<: *setup-node
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v3
      - <<: *setup-node
      - name: install
        run: yarn install --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: markdown lint
        run: yarn lint:md

  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: install-node-modules

    steps:
      - uses: actions/checkout@v3
      - <<: *setup-node
      - name: install
        run: yarn install --frozen-lockfile
      - name: format-check
        run: yarn format:check
